### ISSUE TITLE
Appium PHP error on cmd 

### ISSUE THREAD

**Issue by lemueloodle** [appium/php-client#49]
Hi everyone,

Can you help me fix this issue, i'm getting this error when I execute in CMD:

`phpunit bot.php` 

`PHP Fatal error:  Class 'PHPUnit_Extensions_Selenium2TestCase_Command' not found in D:\xampp\htdocs\shopeephp\PHPUnit\Extensions\AppiumTestCase\SessionCommand\Context.php on line 18`

**Comment by yunsiong** [comment]
Hi, i have same issue, any soluton to fix it?
