### ISSUE TITLE
$driver

### ISSUE THREAD

**Issue by C14427818** [appium/php-client#50]
Not so much an issue but a question. I have seen examples like 

$driver->hideKeyboard();
$driver->hideKeyboard(array(
      'keyName' => 'Done'
));

and was just wondering how to intialise $driver correctly, or can I just use $this->hideKeyboard(); instead?

**Comment by jlipps** [comment]
Yes, if your test class extends `PHPUnit_Extensions_AppiumTestCase`, you would use `$this` as the driver object.
